name: _
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/*

dev_dependencies:
  melos: ^7.4.0

melos:
  scripts:
    test:
      exec: flutter test
      description: Roda os testes unitários em todos os packages
      packageFilters:
        dirExists: test
        ignore:
          - app
